// <auto-generated />
using GuildrAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuildrAPI.Migrations
{
    [DbContext(typeof(GuildrAPIContext))]
    partial class GuildrAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("GuildrAPI.Models.ProfileItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Class");

                    b.Property<string>("Name");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Url");

                    b.Property<int>("Level");

                    b.HasKey("Id");

                    b.ToTable("ProfileItem");
                });
#pragma warning restore 612, 618
        }
    }
}
